"""Tabla usuarios

Revision ID: b848d52d4281
Revises:
Create Date: 2026-05-22 13:47:25.382412

"""

import uuid
from datetime import datetime
from typing import Sequence, Union

import bcrypt
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b848d52d4281"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("full_name", sa.String(255), nullable=False),
        sa.Column(
            "hashed_password",
            sa.String(),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    # ### end Alembic commands ###
    #
    # Usuario dummy para pruebas iniciales
    # Credenciales: admin@yummy.com / Admin1234!
    hashed_password = bcrypt.hashpw(b"Admin1234!", bcrypt.gensalt()).decode()
    now = datetime.now()

    op.execute(
        sa.text(
            "INSERT INTO users (id, email, full_name, hashed_password, is_active, created_at, updated_at) "
            "VALUES (:id, :email, :full_name, :hashed_password, :is_active, :created_at, :updated_at)"
        ).bindparams(
            id=str(uuid.UUID("3201ab56-39fe-4899-a1c0-e85bd56f4bb6")),
            email="admin@yummy.com",
            full_name="Admin User",
            hashed_password=hashed_password,
            is_active=True,
            created_at=now,
            updated_at=now,
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
